version: "3"
services:
  web:
    image: nginx:stable-alpine
    ports:
      - "8083:80"
    volumes:
      - ${OLD_HG_PROJECT_DIR}:/var/www/html:cached
      - ./data/nginx/hg.conf:/etc/nginx/conf.d/default.conf
      # - /tmp:/var/tmp # for xdebug profile file
    depends_on:
      - old-php
      - frontend-nuxt
    # networks: # ? to remove networks?
    #   - webnet
  core-api-web:
    image: nginx:stable-alpine
    ports:
      - 8084:8084
    volumes:
      - ${CORE_API_PROJECT_DIR}:/var/www/html:cached
      - ./data/nginx/core-api.conf:/etc/nginx/conf.d/default.conf
      # - /tmp:/var/tmp # for xdebug profile file
    depends_on:
      - core-api-fpm
  core-api-fpm:
    image: gengsa/php-phalcon:7.2.7-3.4.0
    volumes:
      - ${CORE_API_PROJECT_DIR}:/var/www/html:cached
      - ./data/core-php:/usr/local/etc
      # - /tmp:/var/tmp # for xdebug profile file
  # core-api:
  #   image: gengsa/php-phalcon:7.2.7-3.4.0
  #   volumes:
  #     - ${CORE_API_PROJECT_DIR}:/var/www/html:cached
  #     - ./data/core-php:/usr/local/etc
  #     # - /tmp:/var/tmp # for xdebug profile file
  #   command: sh -c "php artisan serve --host=0.0.0.0 --port=8084"
  #   ports:
  #     - 8084:8084
  old-php:
    image: gengsa/php-phalcon:5.6.36-2.0.13
    volumes:
      - ${OLD_HG_PROJECT_DIR}:/var/www/html:cached
      - ./data/old-php:/usr/local/etc
      # - /tmp:/var/tmp # for xdebug profile file
  frontend-nuxt:
    image: node:lts-alpine
    volumes:
      - ${FRONTEND_PROJECT_DIR}:/var/www/html:cached
      - ~/.npm:/root/.npm:cached
    working_dir: /var/www/html
    # command: sh -c "npm install --loglevel verbose && npm run dev"
    command: sh -c "npm run dev"
    ports:
      - 3000:3000

# networks:
#   webnet:
