version: "3"
services:
  web:
    image: nginx:stable-alpine
    deploy:
      # replicas: 1
      # resources:
      #   limits:
      #     cpus: "0.1"
      #     memory: 50M
      # restart_policy:
      #   condition: on-failure
    ports:
      - "8083:80"
      # maybe need export some port for 443
    volumes:
      - /Users/gengsa/workspace/HG-old:/var/www/html
      - ./data/nginx/hg.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    # networks: # ? to remove networks?
    #   - webnet
  php:
    # replace username/repo:tag with your name and image details
    # image: username/repo:tag
    image: gengsa/php-phalcon:5.6.36-2.0.13
    volumes:
      - /Users/gengsa/workspace/HG-old:/var/www/html
      - ./data/php:/usr/local/etc

# networks:
#   webnet:
